source 'https://rubygems.org'

gem 'wordtree', '0.1.0'
gem 'rethinkdb'
gem 'sinatra'
gem 'unicorn'

group :development, :test do
  gem 'rspec'
  gem 'rack-test'
  gem 'guard'
  gem 'guard-rspec'
  gem 'debugger'
end